apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app-test
    spec:
      containers:
        - name: app
          image: TMPL_image
          imagePullPolicy: Always
          ports:
            - containerPort: 80
