apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: go-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: go-test
    spec:
      containers:
        - name: go-app
          image: TMPL_go_image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
